//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stutdent_Complain_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public string picture { get; set; }
        public string username { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
    }
}
