//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stutdent_Complain_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFroupFeature
    {
        public int UserGroupId { get; set; }
        public int FeartureId { get; set; }
        public bool IsDataPermission { get; set; }
        public bool IsCreatePermission { get; set; }
        public bool IsManagerPermission { get; set; }
    
        public virtual Fearture Fearture { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
